-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
  FROM DOCTOR D 
       INNER JOIN APPOINTMENT A
    ON A.MDDR_ID = D.DR_ID
       INNER JOIN PATIENT P
    ON P.PT_NO = A.PT_NO
 WHERE TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
   AND APNT_CNCL_YN = 'N'
   AND A.MCDP_CD = 'CS'
 ORDER BY APNT_YMD;